### ISSUE TITLE
cat EOF to create shipyard

### ISSUE THREAD

**Issue by agardnerIT** [afzal442/keptn-pg-killerway#5]
Create the shipyard more easily in an `{{execute}}` statement.

Rather than `nano`:

```
cat << EOF > shipyard.yaml
apiVersion: "spec.keptn.sh/0.2.2"
kind: "Shipyard"
metadata:
  name: "shipyard-delivery"
spec:
  stages:
    - name: "qa"
      sequences:
        - name: "delivery"
          tasks:
            - name: "je-deployment"
            - name: "je-test"

    - name: "production"
      sequences:
        - name: "delivery"
          triggeredOn:
            - event: "qa.delivery.finished"
          tasks:
            - name: "je-deployment"
EOF
```
